In [1]:
import pandas as pd

In [2]:
views = pd.read_csv("../data/feed-views.log", sep="\t", names=["datetime", "user"])
views["datetime"] = pd.to_datetime(views["datetime"])
views["year"] = views["datetime"].dt.year
views["month"] = views["datetime"].dt.month
views["day"] = views["datetime"].dt.day
views["hour"] = views["datetime"].dt.hour
views["minute"] = views["datetime"].dt.minute
views["second"] = views["datetime"].dt.second

In [3]:
## Creating a daytime column
bins = [0, 4, 7, 11, 17, 20, 24]
labels = ["night", "early morning", "morning", "afternoon", "early evening", "evening"]

views["daytime"] = pd.cut(
    views["hour"],
    bins=bins,
    labels=labels,
    right=False,
    include_lowest=True
)

In [4]:
## Index
views.set_index("user", inplace=True)

In [5]:
## Number of elements
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [6]:
## Quantity by category daytime
views["daytime"].value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

In [7]:
## Sort by time
views_sorted = views.sort_values(by=["hour", "minute", "second"])

In [8]:
## min/max and time mode
views["hour"].min(), views["hour"].max()
views["datetime"].mode()

0      2020-04-17 12:01:08.463179
1      2020-04-17 12:01:23.743946
2      2020-04-17 12:27:30.646665
3      2020-04-17 12:35:44.884757
4      2020-04-17 12:35:52.735016
                  ...
1071   2020-05-21 18:45:20.441142
1072   2020-05-21 23:03:06.457819
1073   2020-05-21 23:23:49.995349
1074   2020-05-21 23:49:22.386789
1075   2020-05-22 10:36:14.662600
Name: datetime, Length: 1076, dtype: datetime64[ns]

In [9]:
## Maximum hour for night, minimum for morning and who was it
night_max = views[views["daytime"] == "night"]["hour"].max()
morning_min = views[views["daytime"] == "morning"]["hour"].min()

visitor_night = views[views["hour"] == night_max].head(1)
visitor_morning = views[views["hour"] == morning_min].head(1)

In [10]:
## Hour and daytime modes
views["hour"].mode()
views["daytime"].mode()

0    evening
Name: daytime, dtype: category
Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

In [11]:
## 3 earliest visits in the morning and 3 latest hours
morning_users = views[views["daytime"] == "morning"]
morning_users.nsmallest(3, "hour")
views.nlargest(3, "hour")

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-18 23:06:34.198911,2020,4,18,23,6,34,evening
artem,2020-04-18 23:40:32.666884,2020,4,18,23,40,32,evening
artem,2020-04-19 23:10:03.761243,2020,4,19,23,10,3,evening

In [12]:
## Statistics
views[["hour", "minute", "second"]].describe()

              hour       minute       second
count  1076.000000  1076.000000  1076.000000
mean     16.249071    29.629182    29.500929
std       6.955490    17.689388    17.405506
min       0.000000     0.000000     0.000000
25%      13.000000    14.000000    14.000000
50%      19.000000    29.000000    30.000000
75%      22.000000    46.000000    45.000000
max      23.000000    59.000000    59.000000

In [13]:
## Calculating IQR for an hour
desc = views["hour"].describe()
iqr = desc["75%"] - desc["25%"]
iqr

np.float64(9.0)