In [1]:
import pandas as pd

In [2]:
df = pd.read_json("../data/auto.json")
df.set_index("CarNumber", inplace=True)
df.head()

              Refund   Fines    Make  Model
CarNumber
Y163O8161RUS       2  3200.0    Ford  Focus
E432XX77RUS        1  6500.0  Toyota  Camry
7184TT36RUS        1  2100.0    Ford  Focus
X582HE161RUS       2  2000.0    Ford  Focus
92918M178RUS       1  5700.0    Ford  Focus

In [3]:
## Simple Selects
df[df["Fines"]> 2100]
df[(df["Fines"]> 2100) & (df["Refund"] == 2)]
df[df["Model"].isin(["Focus", "Corolla"])]
numbers = ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']
df.loc[df.index.isin(numbers)]

              Refund          Fines  Make  Model
CarNumber
92928M178RUS       1    8594.586466  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
Y7689C197RUS       1   27000.000000  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
H115YO163RUS       1    8594.586466  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
7788KT197RUS       2    8594.586466  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus

In [4]:
## brand and model
df.groupby("Make")["Fines"].median()
df.groupby(["Make", "Model"])["Fines"].median()
df.groupby("Make")["Fines"].count()
df.groupby(["Make", "Model"])["Fines"].agg(["min", "max"])
df.groupby(["Make", "Model"])["Fines"].std()

Make        Model
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen  Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Name: Fines, dtype: float64

In [5]:
## car number
fine_counts = df.groupby(df.index)["Fines"].count().sort_values(ascending=False)
top_car = fine_counts.index[0]
df.loc[top_car]
fine_sums = df.groupby(df.index)["Fines"].sum().sort_values(ascending=False)
fine_sums
top_car_sum = fine_sums.index[0]
df.loc[top_car_sum]

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2   24200.0  Ford  Focus
X758HY197RUS       2   72600.0  Ford  Focus
X758HY197RUS       2  145200.0  Ford  Focus

In [6]:
## different models
multiple_models = df.groupby(df.index)["Model"].nunique()
multiple_models[multiple_models > 2]

Series([], Name: Model, dtype: int64)